name: speedstar_core
description: Shared core for SpeedStar apps.
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_remote_config: ^6.1.4
  cloud_firestore: ^6.1.2
  location: ^6.0.2
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
